### ISSUE TITLE
The type registry does not know about type id

### ISSUE THREAD

**Issue by yissachar** [spring-projects/spring-loaded#165]
I'm receiving the following exception when using hot-reload with the [Lettuce Redis library](https://github.com/mp911de/lettuce):

```
Caused by: java.lang.IllegalStateException: The type registry TypeRegistry(id=1346265082,loader=java.net.URLClassLoader) does not know about type id 901
    at org.springsource.loaded.TypeRegistry.getReloadableType(TypeRegistry.java:1688)
    at org.springsource.loaded.TypeRegistry.idyrun(TypeRegistry.java:1572)
    at com.lambdaworks.redis.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:182)
    at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:157)
    at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:154)
    at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:138)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    ... 1 more
```

Here is the line in question:

```
protected void safeSet(CommandOutput<K, V, ?> output, ByteBuffer bytes, RedisCommand<K, V, ?> command) {
    safeSet(() -> output.set(bytes), command);
}
```

**Comment by longwa** [comment]
I'm seeing the same thing reloading in a Grails app using Chronicle-Map to store off-heap data.

**Comment by gferon** [comment]
I'm also seeing this issue with [jsass](https://github.com/bit3/jsass) that is also using lambda expressions from Java 8.

Should we have any hope to see this fix for a future version and Grails 2.x?

**Comment by aclement** [comment]
If anyone has a complete simple project they can share that demonstrates the problem, that is likely to speed up getting it fixed.

**Comment by gferon** [comment]
Thanks! I just published [a sample project to reproduce the issue](https://github.com/gferon/spring-loaded-issue-165).

Just run the app with the Grails wrapper and JDK8, and the two URLs:
- http://localhost:8080/spring-loaded-issue-165/test/failWithoutLibrary
- http://localhost:8080/spring-loaded-issue-165/test/failWithLibrary

As soon as you make any change to the app (and I guess springloaded is used) the exception gets thrown and the app is rendered useless.

**Comment by gferon** [comment]
I just pushed a failing unit test on my fork of springloaded.

**Comment by gferon** [comment]
The test commits I made actually fix a different bug not the one described in this ticket :open_mouth:

**Comment by mischkl** [comment]
Same issue here! Any word on this?

**Comment by lquterqtd** [comment]
i have seen the same exception,also the lambda expression

**Comment by equilibric** [comment]
+1 - errors out on reload on a line that contains a lambda expression in library that is a dependency.

**Comment by craigraw** [comment]
This issue appears to occur when using Moneta, the javax.money RI implementation. No hot reloading is possible in a Grails 3 app with that dependency.

**Comment by johngamarra** [comment]
+1

**Comment by timic** [comment]
+1

**Comment by zyro23** [comment]
same issue (or at least stacktrace) with selenium 3.
```
Caused by: java.lang.IllegalStateException: The type registry TypeRegistry(id=1420603454,loader=sun.misc.Launcher$AppClassLoader) does not know about type id 5836
    at org.springsource.loaded.TypeRegistry.getReloadableType(TypeRegistry.java:1910)
    at org.springsource.loaded.TypeRegistry.idyrun(TypeRegistry.java:1789)
    at org.openqa.selenium.remote.ErrorCodes.toState(ErrorCodes.java:116)
    at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConverter.java:138)
    at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConverter.java:46)
    at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:79)
    at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
```
offending code:
```
Set<String> possibleMatches = KNOWN_ERRORS.stream()
      .filter(knownError -> knownError.getJsonCode() == status)
      .filter(KnownError::isCanonicalForW3C)
      .map(KnownError::getW3cCode)
      .collect(Collectors.toSet());
```
communication with the remote webdriver browser fails after that so it is not just the reload that does not happen but the running app is affected.

also tried to exclude via `exclusions=org.openqa.selenium..*` - didnot help.

i think this issue is a real blocker because it happens if _any_ class is reloaded, no matter if completely unrelated to the offending code.

if fixing the root cause is complicated, it would be great if at least excluding works in the meantime.

**Comment by mischkl** [comment]
What is going on with the spring-loaded project in general? Seemingly no development since June, Java 8 code is still broken even though it's been out for two and half years... I guess everyone has moved on to HotSwap agent, or JRebel?

**Comment by mlaccetti** [comment]
I switched to springloaded simply because JRebel became so damn expensive - be miserable for it to simply rot into nothingness.

**Comment by shot-mk** [comment]
+1

**Comment by animator013** [comment]
+1

**Comment by bwolin** [comment]
+1 seeing this with lucene in a grails 3 project

**Comment by ccozzolino** [comment]
+1

**Comment by todd-elvers** [comment]
+1 I'm also seeing this on Grails 3.2.6 when using libraries containing lambdas.  

Is there no workaround for this?

**Comment by stiancor** [comment]
+1

**Comment by emitrohin** [comment]
+1

**Comment by pocket5s** [comment]
+1

**Comment by sdelamo** [comment]
+1

**Comment by graemerocher** [comment]
I have submitted a pull request for this. @aclement Any chance of you could review, merge and doing a 1.2.7 release?

**Comment by graemerocher** [comment]
@aclement I also submitted https://github.com/spring-projects/spring-loaded/pull/196 which fixes a common issue with reloading types that use Lambdas.

**Comment by ccozzolino** [comment]
Confirmed that @graemerocher fix works for me

**Comment by mateusmarquezini** [comment]
I'm trying to use Spring Loaded version 1.2.7-RELEASE and I'm getting this error every time when I try to make project again on IntelliJ. Does anybody still get this error?

**Comment by animator013** [comment]
I think it is fixed in 1.2.8.BUILD-SNAPSHOT.

**Comment by mateusmarquezini** [comment]
thanks @animator013 , I will check this!

**Comment by selimok** [comment]
In my case 1.2.8-SNAPSHOT doesn't solve my problem. 

Part of the stack trace:
```
Caused by: java.lang.IllegalStateException: The type registry TypeRegistry(id=1088488879,loader=sun.misc.Launcher$AppClassLoader) does not know about type id 747
	at org.springsource.loaded.TypeRegistry.getReloadableType(TypeRegistry.java:1910) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.springsource.loaded.TypeRegistry.idyrun(TypeRegistry.java:1789) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at com.vaadin.server.communication.LegacyUidlWriter.sortByHierarchy(LegacyUidlWriter.java:91) ~[vaadin-server-8.0.0.jar:8.0.0]
```

Problematic part of the code (LegacyUidlWriter.java:91): 

```
 Collections.sort(paintables, (Component c1, Component c2) -> {
...
```

**Comment by animator013** [comment]
@selimok are you sure you are using the 1.2.8 version ? From the exception i see 
```
~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE
```

**Comment by selimok** [comment]
@animator013 thanks for asking, but that was the code dependency for triggering auto reload of UI components. Agent version was 1.2.8-SNAPSHOT downloaded from the link you provided above. 
```
-javaagent:/Devel/libs/springloaded-1.2.8.jar -noverify
```

**Comment by animator013** [comment]
Well it seems it is still not working correctly.

```
The type registry TypeRegistry(id=1385128737,loader=sun.misc.Launcher$AppClassLoader) does not know about type id 2497. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at sk.creativeweb.accomodation.filter.CorsFilter.doFilterInternal(CorsFilter.groovy:29)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I am using the 1.2.8-snapshot version. There is still some work which has to be done to correct the reloading.

This issue should be reopened.

**Comment by graemerocher** [comment]
Provide an example that reproduces the problem and we can reopen. Random reports without concrete examples aren't useful.

**Comment by animator013** [comment]
I think @selimok provided one. I need to further investigate this, it's something odd.

**Comment by selimok** [comment]
Here a ready to execute example: https://github.com/selimok/spring-boot-loaded-vaadin

**Comment by selimok** [comment]
@animator013 you were right. Although I passed the right version of springloaded version via -javaagent parameter, in project dependency avoided loading right version of springloaded. After changing pom dependency as 1.2.8.BUILD-SNAPSHOT, the problem is gone.

Sorry for false alarm and thanks for the great work :)

**Comment by dekay2323** [comment]
I have a similar bug and code to duplicate I am not sure what is causing it.
Here is the code and details
https://github.com/dekay2323/TypeRegistry
