### ISSUE TITLE
ReloadableType can not access a member of class...

### ISSUE THREAD

**Issue by marcuslange** [spring-projects/spring-loaded#166]
java.lang.IllegalAccessException: Class org.springsource.loaded.ReloadableType can not access a member of class org.springframework.context.annotation.ConfigurationClassEnhancer$BeanFactoryAwareGeneratorStrategy with modifiers "public"
        at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:101)
        at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:295)
        at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:287)
        at java.lang.reflect.Method.invoke(Method.java:476)
        at org.springsource.loaded.ReloadableType.reloadProxiesIfNecessary(ReloadableType.java:597)
        at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:446)
        at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:1014)
        at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:104)
        at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:251)
        at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:235)
        at java.lang.Thread.run(Thread.java:745)

**Comment by gtekel** [comment]
i have this problem too.

**Comment by axelfontaine** [comment]
+1

**Comment by wbenass** [comment]
+2

**Comment by wbenass** [comment]
I actually added this (-Dspringloaded=explain) to my command line and after I attempted a change to a very simple boot application I received more diagnostics that might shed some light if you do the same.

java.lang.IllegalAccessException: Class org.springsource.loaded.ReloadableType can not access a member of class org.springframework.context.annotation.ConfigurationClassEnhancer$BeanFactoryAwareGeneratorStrategy with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Unknown Source)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(Unknown Source)
	at java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springsource.loaded.ReloadableType.reloadProxiesIfNecessary(ReloadableType.java:568)
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:446)
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:1014)
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:104)
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:251)
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:235)
	at java.lang.Thread.run(Unknown Source)
2016-02-09 16:12:23.900  INFO 23672 --- [ndardContext[]]] org.springsource.loaded.TypeRegistry     : WhyNotReloadable? The type org/apache/catalina/webresources/Cache$EvictionOrder is using a package name 'org/apache/' which is considered infrastructure and types within it are not made reloadable
2016-02-09 16:12:23.900  INFO 23672 --- [ndardContext[]]] org.springsource.loaded.TypeRegistry     : WhyNotReloadable? The type org/apache/catalina/webresources/Cache$EvictionOrder is using a package name 'org/apache/' which is considered infrastructure and types within it are not made reloadable
2016-02-09 16:12:23.900  INFO 23672 --- [ndardContext[]]] org.springsource.loaded.TypeRegistry     : WhyNotReloadable? The type org/apache/catalina/webresources/CachedResource is using a package name 'org/apache/' which is considered infrastructure and types within it are not made reloadable
2016-02-09 16:12:23.900  INFO 23672 --- [ndardContext[]]] org.springsource.loaded.TypeRegistry     : WhyNotReloadable? The type org/apache/catalina/webresources/CachedResource is using a package name 'org/apache/' which is considered infrastructure and types within it are not made reloadable
2016-02-09 16:12:23.901  INFO 23672 --- [ndardContext[]]] org.springsource.loaded.TypeRegistry     : WhyNotReloadable? The type org/apache/tomcat/PeriodicEventListener is using a package name 'org/apache/' which is considered infrastructure and types within it are not made reloadable
2016-02-09 16:12:23.901  INFO 23672 --- [ndardContext[]]] org.springsource.loaded.TypeRegistry     : WhyNotReloadable? The type org/apache/tomcat/PeriodicEventListener is using a package name 'org/apache/' which is considered infrastructure and types within it are not made reloadable

**Comment by wbenass** [comment]
And per the wiki:

org/springframework/
org/hibernate/
org/hsqldb/
org/aspectj/
org/xml/
org/h2/


If you use one of these packages as your application package prefix, it will not be made reloadable at the moment.

**Comment by wbenass** [comment]
I think it boils down to whether it is characterized reloadable or not based on packages it uses.  I did get this to work in my classes that don't use org/apache, org/springframework, etc.

**Comment by rafaelNaranjo** [comment]
+ 3

**Comment by skeeey** [comment]
me too

**Comment by rzymek** [comment]
This exception happens when using Spring Loaded `1.2.5.RELEASE` with Sprint Boot versions `1.3.1.RELEASE` to `1.3.3.RELEASE`.  **It works fine with Spring Boot `1.3.0.RELEASE`**.

Here's a minimal project to reproduce the problem: https://github.com/rzymek/sprint-boot-loaded
Tested using Oracle JDK:

    java version "1.8.0_74"
    Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
    Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

**Comment by aclement** [comment]
Thanks @rzymek for the test code, always invaluable. I just pushed a potential fix - performing a setAccessible prior to the reflective invocation. Looks like some visibility changes in more recent boots may now mean that is required. ( I'll admit I haven't checked that the app behaves as expected now the exception is addressed though).  1.2.6.BUILD-SNAPSHOTs should include the change, there will probably be a 1.2.6 release shortly.

**Comment by jgnan** [comment]
Hello everyone, I'm using spring-boot 1.3.2.RELEASE with tomcat server, still having the same problem. Do you have any suggestion for me to fix this bug to my situation?
